// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbFPRXj_RX0VCk_v_TXzEQT_IrhYXc2TI',
    appId: '1:1063145260614:web:9342a79672ea08e1516c47',
    messagingSenderId: '1063145260614',
    projectId: 'livedemo-39597',
    authDomain: 'livedemo-39597.firebaseapp.com',
    storageBucket: 'livedemo-39597.appspot.com',
    measurementId: 'G-73PDTD3MJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqO1wfJBYyJhblkneQFVY1JwtIP0UK5k8',
    appId: '1:1063145260614:android:cb069ddf0f6dfdcc516c47',
    messagingSenderId: '1063145260614',
    projectId: 'livedemo-39597',
    storageBucket: 'livedemo-39597.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPsUR8fvuuOLWDifkn9_m5MEBj60BHfE8',
    appId: '1:1063145260614:ios:c5cf0d189106feac516c47',
    messagingSenderId: '1063145260614',
    projectId: 'livedemo-39597',
    storageBucket: 'livedemo-39597.appspot.com',
    iosBundleId: 'com.example.firestoreBspBenni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPsUR8fvuuOLWDifkn9_m5MEBj60BHfE8',
    appId: '1:1063145260614:ios:33b71d6e0c144a14516c47',
    messagingSenderId: '1063145260614',
    projectId: 'livedemo-39597',
    storageBucket: 'livedemo-39597.appspot.com',
    iosBundleId: 'com.example.firestoreBspBenni.RunnerTests',
  );
}
